* 0.6.2 (Released 2017-03-22)
  * Even if sidebar is hidden, the toolbar button always said it was enabled.
  * Archive used to only archive the current subtree and it ignored selections.  Now it archives the entire selection
    too, even if it is multiple subtrees.
  * Indicate in settings that multiple predefined directories should be separated with a comma.
  * If there are links inside of an agenda or todo item, render them as hyperlinks
  * If there is bold or underlined text in an agenda or todo item, render them.

* 0.6.1 (Released 2017-03-18)
  * Missed adding some files before I released, re-releasing.  This closes issue #14.

* 0.6.0 (Released 2017-03-17)
  * New Agenda sidebar panel
  * Any item marked with a SCHEDULED tag later than or equal to the
    start of today will show up in the Agenda Panel of the sidebar.
  * New archive command (ctrl-i a) which moves the current subtree you are pointing to into a file named
    <current-filename>_archive.  (For example, for TODO.org, it would be moved to TODO.org_archive)
  * Archive files are now colored by org-mode as well.
  * Stop using COMPLETED for todo items.  Instead use DONE.  Existing COMPLETED tags will continue to be colored
    correctly.
  * Don't require brackets around TODO items.
  * Add a setting which asks whether we should use brackets around TODO or DONE by default

* 0.5.8 (Released 2017-03-16)
  * Fixed problem where completing a todo item from the sidebar would leave the TODO tag in place.
  * Fixed problem where clicking on todo items in sidebar wouldn't bring you to the correct file if the file came
    from the search path.
  * Add key command to add a schedule completion date (default ctrl-i s), defaulting to today.  This should be
    considered beta.

* 0.5.7 (Released 2017-03-15)
  * Fixed case where pressing enter on a non-star-line would cause an exception if the next line had a star.
  * Fixed error leading to an empty sidebar when a predefined search file or directory does not exist.
  * Added support for R-language for code blocks
  * Fix deprecation warnings due to removal of Shadow DOM
  * Fixed color coding for CLOSED and SCHEDULED tags.  (They haven't been working for quite a while.)
  * Added golang support for code blocks
  * Fix coloring for stars

* 0.5.6 (Released 2016-03-15)
  * This change was never officially released to the public and were rolled up into 0.5.7

* 0.5.5 (Released 2016-11-30)
  * Minor documentation improvements

* 0.5.4 (Released 2016-11-29)
  * Fixed ctrl-return indenting if you are making outlines or stacked symbols.  Previously this would always
    indent two spaces, even though that wasn't right for those cases.
  * Rethought the "organized.indentType" setting a bit.  Rather than specifying tabs or spaces directly, now
    we'll use your editors normal setting (editor->tabType) instead.  This should make things work more
    correctly by default for people that use tabs by default.
  * As part of this rethinking, removed indentSpaces setting in favor of editor.tabLength setting.
  * Fixed bug with indenting -- if a bullet character (-,+,*) were embedded in the middle of a line, we would not
    indent that line along with the rest of your bullet.
  * Modified the searchDirectories setting to allow setting files in addition to directories.
  * Fixed bug preventing you from hitting return from the beginning of the second line of a section like this:
    #Section
    Some list:
      1. One
      2. Two
      3. Three
  * Fix table close command, which was erroring out due to a regex error.

* 0.5.3 (Released 2016-11-18)
  * Fix for Issue #7 - if a star is followed by a linebreak, that should be treated line a star too.
  * Fix for Issue #8 - when indenting, try to detect indent type even if it is different from the default type
  * Organized was not obeying the config setting for the number of spaces, it was only using the editor style.  Now
    it should obey the config setting.

* 0.5.2 (Released 2016-11-18)
  * Fix for regular expression error.  (Thanks to John Kamenik for the PR!)

* 0.5.1 (Release 2016-09-20)
  * rbenson-patch-1 PR  (Thanks Ryan Benson for the PR!)

* 0.5.0 (Released 2016-09-08)
  * Added sidebar, which shows TODO's from all .org files in the current project.
    * Use menus (Packages -> Organized) or the command organized:toggleSidebar
      to toggle whether the menu appears.
    * Todos can be marked as done by checking the checkbox next to them.
    * Navigate to the source of the todo by clicking on the text.
    * Refresh todos by clicking on the refresh button.  Todos are also refreshed
      any time an organized file is saved.
    * Added setting that allows additional directory names to be specified to scan.
    * Added setting that allows you to exclude project directories from TODO scan.
    * Added setting that allows certain files to be excluded.
    * Added ability to resize sidebar
    * Don't select text in sidebar while resizing.
    * This feature is coming along, but is still in a fairly beta state.
  * Fixed some toolbar quirkiness - should appear correctly now when enabled in settings.

* 0.4.2 (Released 2016-09-01)
  * Fixed missing file preventing installation

* 0.4.1 (Released 2016-09-01)
  * Minor toolbar improvements
    * Toolbar can be disabled through the organized setup, even if you have toolbar installed
    * Menu item installed to toggle the toolbar, which should raise the visibility that there is a toolbar.
  * Fix bug which caused 0.4.0 not to install correctly!
  * Bug fixes
    * Don't hijack result blocks from other code blocks.  Previously, if there were two code blocks and a result
      block, executing the first code block would be the results in the result block.  Only the second one should.

* 0.4.0 (Released 2016-08-31)
  * Support the "tool-bar" package for atom -- if it is installed, organized will have a toolbar with buttons for:
    * Indent
    * Unindent
    * Creating Headings
    * Bold
    * Underline
    * Creating Links
    * Creating Tables
    * Create code blocks
    * Execute code blocks
    * Create result blocks to display the code blocks

* 0.3.2 (Released 2016-08-30)
  * Added support for code execution for php and perl
  * Early support for code execution for Java
    * Doesn't include ability to add any libraries to the classpath.  That will come in a later release.
  * Early support for code execution in C and C++
    * Doesn't include ability to set any kind of c-like library paths or options.
  * Early support for code execution in Objective-C
    * Currently I call "clang -lobjc -framework Foundation -o <temp output file> <temporary filename>" to compile.
    * Just as with the others above, this will need better support for libraries
  * Bug fixes
    * If you are on a level N outline and there is already a level N+1 indent underneath and you press return, then
      new line should be on level N+1, not on level N.
    * Support multiple cursors for TODO toggling.

* 0.3.1 (Released 2016-08-30)
  * Bug Fixes
    * Intend and unindent works correctly with multiple cursors

* 0.3.0 (Released 2016-08-29)
  * Early support for tables
    * Syntax highlighting for the borders of tables
    * Commands to automatically open (create the first line of) or close (create the last line of) a table
  * Text styling
    * __Bold__ Text
    * _Underlined_ Text
  * Bug fixes
    * Fixed tab and shift-tab if you aren't in the context of a star.  They'll perform editor.indentSelectedRows() and
      editor.outdentSelectedRows() respectively.
    * Tags were able to include spaces, which made some rather unusual things being matched.
    * When you are using stacked stars (like *** for a third level star), when you press enter, it should
      continue to use that outline type.

* 0.2.1 (Released 2016-08-24)
  * Highlighting for links
  * Support org-mode style BEGIN_SRC/END_SRC code tags for source code
  * Bug Fixes
    * Can't hit return when I'm on a header row

* 0.2.0 (Released 2016-08-22)
  * Added support for inserting current ISO-8601 date / datetime (ctrl-i d or ctrl-i t respectively)
  * Added support for embedded codeblocks using jira style code blocks
    ```shell
    <some shell commands>
    ```
  * Syntax highlighting for SCHEDULED tags on outline items.
  * Syntax highlighting for tags
  * Fixed bugs
    * If you weren't at the end of the line when you pressed return, the text after your cursor was deleted.
    * If your cursor was before the star, the behavior would be incorrect.

* 0.1.0 (Released 2016-08-21)
  * Added support for using numbers as bullets
  * More test cases and bug fixes.
  * Fixed console error on startup

* 0.0.2 (Released 2016-08-20)
  * Highlighting of stars
  * Toggle for todo items
  * Support for markdown-style headers
  * Auto-create asterisk on new line when you hit return (configurable)
  * Don't create a star on a new line if you hit ctrl-enter and line up indent with text (configurable)
  * Support indent (tab) and unindent (shift-tab) commands with autodetection
    of which style you have been using.
